# Generated by Django 3.1.12 on 2025-02-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20250201_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deployment_time_hr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cost_per_operation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_available', models.IntegerField()),
            ],
        ),
    ]
