# Generated by Django 3.1.12 on 2025-02-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_historicalenvironmentaldata_historicalfireevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureEnvironmentalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vegetation_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('human_activity_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
        ),
    ]
