# Generated by Django 3.1.12 on 2025-02-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_futureenvironmentaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='units_available',
        ),
    ]
