# Generated by Django 3.1.12 on 2025-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_resource_units_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedFireEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
        ),
    ]
